// DashboardEntity
// This file was auto-Generated by Flutter Bunny Cli🐰

class DashboardEntity {
  final String id;
  final String name;
  // Add more fields as needed

  DashboardEntity({
    required this.id,
    required this.name,
  });
}
