// SettingsEntity
// This file was auto-Generated by Flutter Bunny Cli🐰

class SettingsEntity {
  final String id;
  final String name;
  // Add more fields as needed

  SettingsEntity({
    required this.id,
    required this.name,
  });
}
