// UserProfileUseCase
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../entities/user_profile_entity.dart';
import '../repositories/user_profile_repository.dart';

class GetUserProfileUseCase {
  final UserProfileRepository repository;

  GetUserProfileUseCase(this.repository);

  Future<List<UserProfileEntity>> execute() {
    return repository.getAll();
  }
}

class GetUserProfileByIdUseCase {
  final UserProfileRepository repository;

  GetUserProfileByIdUseCase(this.repository);

  Future<UserProfileEntity> execute(String id) {
    return repository.getById(id);
  }
}
