// DashboardWidget
// This file was auto-Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class DashboardWidget extends StatelessWidget {
  const DashboardWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Dashboard Feature'),
    );
  }
}
