// DashboardRepositoryImpl
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../../domain/entities/dashboard_entity.dart';
import '../../domain/repositories/dashboard_repository.dart';
import '../datasources/dashboard_data_source.dart';
import '../models/dashboard_model.dart';

class DashboardRepositoryImpl implements DashboardRepository {
  final DashboardDataSource dataSource;

  DashboardRepositoryImpl({
    required this.dataSource,
  });

  @override
  Future<List<DashboardEntity>> getAll() async {
    final result = await dataSource.getAll();
    return result.map((model) => model).toList();
  }

  @override
  Future<DashboardEntity> getById(String id) async {
    return await dataSource.getById(id);
  }

  @override
  Future<void> create(DashboardEntity entity) async {
    await dataSource.create(DashboardModel.fromEntity(entity));
  }

  @override
  Future<void> update(DashboardEntity entity) async {
    await dataSource.update(DashboardModel.fromEntity(entity));
  }

  @override
  Future<void> delete(String id) async {
    await dataSource.delete(id);
  }
}
