// DashboardPage
// This file was auto-Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';
import '../widgets/dashboard_widget.dart';

class DashboardPage extends StatelessWidget {
  const DashboardPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Dashboard'),
      ),
      body: DashboardWidget(),
    );
  }
}
