// DashboardRepository interface
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../entities/dashboard_entity.dart';

abstract class DashboardRepository {
  Future<List<DashboardEntity>> getAll();
  Future<DashboardEntity> getById(String id);
  Future<void> create(DashboardEntity entity);
  Future<void> update(DashboardEntity entity);
  Future<void> delete(String id);
}
