// DashboardUseCase
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../entities/dashboard_entity.dart';
import '../repositories/dashboard_repository.dart';

class GetDashboardUseCase {
  final DashboardRepository repository;

  GetDashboardUseCase(this.repository);

  Future<List<DashboardEntity>> execute() {
    return repository.getAll();
  }
}

class GetDashboardByIdUseCase {
  final DashboardRepository repository;

  GetDashboardByIdUseCase(this.repository);

  Future<DashboardEntity> execute(String id) {
    return repository.getById(id);
  }
}
