// DashboardDataSource
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../models/dashboard_model.dart';

abstract class DashboardDataSource {
  Future<List<DashboardModel>> getAll();
  Future<DashboardModel> getById(String id);
  Future<void> create(DashboardModel model);
  Future<void> update(DashboardModel model);
  Future<void> delete(String id);
}

class DashboardRemoteDataSource implements DashboardDataSource {
  // TODO: Implement remote data source (API calls, etc.)

  @override
  Future<List<DashboardModel>> getAll() async {
    // TODO: Implement API call
    return [];
  }

  @override
  Future<DashboardModel> getById(String id) async {
    // TODO: Implement API call
    throw UnimplementedError();
  }

  @override
  Future<void> create(DashboardModel model) async {
    // TODO: Implement API call
  }

  @override
  Future<void> update(DashboardModel model) async {
    // TODO: Implement API call
  }

  @override
  Future<void> delete(String id) async {
    // TODO: Implement API call
  }
}

class DashboardLocalDataSource implements DashboardDataSource {
  // TODO: Implement local data source (shared prefs, database, etc.)

  @override
  Future<List<DashboardModel>> getAll() async {
    // TODO: Implement local storage retrieval
    return [];
  }

  @override
  Future<DashboardModel> getById(String id) async {
    // TODO: Implement local storage retrieval
    throw UnimplementedError();
  }

  @override
  Future<void> create(DashboardModel model) async {
    // TODO: Implement local storage saving
  }

  @override
  Future<void> update(DashboardModel model) async {
    // TODO: Implement local storage updating
  }

  @override
  Future<void> delete(String id) async {
    // TODO: Implement local storage deletion
  }
}
