// AuthenticationPage
// This file was auto-Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';
import '../widgets/authentication_widget.dart';

class AuthenticationPage extends StatelessWidget {
  const AuthenticationPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Authentication'),
      ),
      body: AuthenticationWidget(),
    );
  }
}
