// AuthenticationEntity
// This file was auto-Generated by Flutter Bunny Cli🐰

class AuthenticationEntity {
  final String id;
  final String name;
  // Add more fields as needed

  AuthenticationEntity({
    required this.id,
    required this.name,
  });
}
