// DashboardModel
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../../domain/entities/dashboard_entity.dart';

class DashboardModel extends DashboardEntity {
  DashboardModel({
    required String id,
    required String name,
  }) : super(
          id: id,
          name: name,
        );

  factory DashboardModel.fromJson(Map<String, dynamic> json) {
    return DashboardModel(
      id: json['id'],
      name: json['name'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
    };
  }

  factory DashboardModel.fromEntity(DashboardEntity entity) {
    return DashboardModel(
      id: entity.id,
      name: entity.name,
    );
  }
}
